# Paths
data_path: ${IMAGENET_TRAIN}
initial_checkpoint: ${IBOT_CHECKPOINT}
output_dir: ${IBOT_OUTPUT_DIR}

# Model
arch: vit_small

# Loss and teacher
lambda1: 1.0
lambda2: 1.0
momentum_teacher: 0.996
teacher_temp: 0.07
teacher_patch_temp: 0.07
warmup_teacher_temp_epochs: 30

# Training
# Number of epochs to train after loading the checkpoint.
epoch: 50
gpu_count: 4
batch_size_per_gpu: 64
seed: 0
use_fp16: true
clip_grad: 3.0
freeze_last_layer: 1

# Optimizer and schedules
optimizer: adamw
lr_schedule: cosine
lr: 0.0005
min_lr: 0.000001
warmup_epochs: 10
weight_decay: 0.04
weight_decay_end: 0.4

# Data loading
num_workers: 10
